name: KQL Bot

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  generate-kql:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/kql')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '/kql'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate KQL
        id: gen
        env:
          ISSUE_COMMENT: ${{ github.event.comment.body || github.event.issue.body }}
        run: python main.py

      - name: Reply with KQL
        uses: actions/github-script@v7
        with:
          script: |
            const kql = `${{ steps.gen.outputs.kql }}`;
            const body = [
              "### 🎯 Generated KQL Query",
              "",
              "```kql",
              kql,
              "```",
              "",
              "_Generated automatically by The Isaacs Group Sentinel KQL Bot_"
            ].join("\n");

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body
            });
